### ISSUE TITLE
Items outside of network make app crash/unresponsive

### ISSUE THREAD

**Issue by on-d-mand** [jurgenheine/com.tuya.cloud#10]
When there are items outside of your network (let's say a light bulb in another home) it seems the app behaves in strange ways. For instance you can't login from the plugin and if you where already logged in every item becomes unavailable (timeouts etc).

Added light bulbs from any household is possible in the Tuya app and so is adding more then one house.

Suggestion: Either the item should be addressable or 'unavailable' to homey.

**Comment by jurgenheine** [comment]
I think this problem outside the app, the app is just using a cloud API. Is working correctly from phone app?

**Comment by on-d-mand** [comment]
[Sorry Jurgen, been quite a busy time...]

Within the tuya app all the lights worked great even outside of the network (my neighbours told me the lights where off whilst I was in the other house that's on the same account).

Only way to use this plugin for Homey was to remove the lights that where not in the same network
