### ISSUE TITLE
tyua drivers

### ISSUE THREAD

**Issue by ronwell74** [jurgenheine/com.tuya.cloud#101]
hi I am getting messages about deprecate drivers for my tyua devices, i went to the forum link, but it suggested reinstalling the devices, and I got the message to configure the app, but nothing had changed. from what I understand. my devices will still work for now, but if I remove them I won't be able to install them again. how do I fix the driver issues
thanks

**Comment by Pieke21** [comment]
I have the same problem, I reinstalled all my tuya devices. So delete the old ones and reinstall all your tuya cloud devices. Then change where they are situated in what room, and than change all your flows. Now everything is working, a lot of work when you have more then 40 devices and a lot of flows!
Curtain devices are not found in reinstall or regarded as light bulbs. So there is something wrong in app!

**Comment by ronwell74** [comment]
i just it working by going to the IOT tuya site and created an api project.
once i put the api secret in the tuya app all my devices syarted working
again without having to reinstall them.

**Comment by jurgenheine** [comment]
As in message the old API is depricated and Tuya will shut it down. It's not my something I want, but Tuya. It was an unofficial API and official one was not open when this app was created. So it can be working for today, but tomorow maybe not anymore, so switch asap to new API. Maybe not all devices will work directly, but go to forum for workarrounds. This is for bugs and device requests only. I will close this issue, the curtains are already in other issue.

**Comment by ronwell74** [comment]
does the new api give local access to devices?

**Comment by jurgenheine** [comment]
It's a cloud API, no local access. There is an other Homey app for local access.

**Comment by ronwell74** [comment]
i have set up the api and secret in homey. but i am still getting the
depreciation and driver messages. have i missed something
