### ISSUE TITLE
skill id invalid

### ISSUE THREAD

**Issue by eelko123** [jurgenheine/com.tuya.cloud#103]
Hey guys and girls,
I have added tuya devices to homey a few months ago... a lengthy process but happy it is finished (and it worked!)
By means of the homey update legacy no longer functions, and I need to update API to official.

I don't seem to work out the steps to follow... 

I removed all my devices from Homey (not sure if this was a wise thing to do)
I removed one device in Tuya app and re-added it (not sure if this is needed) > do I need to remove all in tuya app?

I have created a new project on IoT development page of Tuya (not sure if this is needed)
Put new Access ID and Access secret code based on the new project (not sure if this was needed) > do I need to use a different Access ID code?

Linked it again to the tuya app.

**Problem**: when I put the Tuya app to 'official only' I keep getting " error: error: code: 2406; msg: skill id invalid"

Now I now I lack some skills by default, however, I would like to get my lights re-installed. What do I need to do?

![Screenshot_20220824-140546_Homey](https://user-images.githubusercontent.com/111982572/186414345-b195d7f4-dd43-44d3-8713-508edb4be12f.jpg)

**Comment by jurgenheine** [comment]
I want bugs here only, no support. Forum is for support. Go to first forum post and you will find the error code there and howto's
