### ISSUE TITLE
Window opener not working

### ISSUE THREAD

**Issue by Mau1971** [jurgenheine/com.tuya.cloud#109]
Dear developer,
In the old Tuya app I can control the window opener. In the new Tuya cloud app (Yuya IoT Platform) I can't control the window opener.
It seems that the catagory is wrong? it is in the Tuya IoT a catagory mc and therefore only showing the window openers in contact sensor and not in windowcovering. See attachment.
Is it possible to get this working again?
Thank you very much for your time,
Maurice.
![Tuya cloud](https://user-images.githubusercontent.com/112470311/187385626-aeed1dfc-a445-47af-8848-fd4639905923.jpg)

**Comment by Mau1971** [comment]
![IoT](https://user-images.githubusercontent.com/112470311/187388641-94b6aca5-7e95-431d-9382-cac97d1bd265.jpg)

**Comment by jurgenheine** [comment]
Fixed in commit a392b96bd6b6a2cc6a03d3292997cc5c6eaa0b94
