### ISSUE TITLE
No separate switches after installing new API

### ISSUE THREAD

**Issue by TripleAx** [jurgenheine/com.tuya.cloud#111]
With the use of Legacy before the update of the new API, i had two different switches displayed from one switch and used some flows on it. (Like Lamp outdoor and Lamp Hallway) and ( Lamp upstairs and Led strip stair)
Now these switches are only within the switch and cannot use flows with it anymore. 

For switch 1 and switch 2 i had two different tabs and could use flows on either 1 or two. Now not possible anymore?

**Comment by TripleAx** [comment]
For switch 1 and switch 2 i had two different tabs and could use flows on either 1 or two. Now not possible anymore?

**Comment by TripleAx** [comment]
![Uploading 240B0ED3-3A95-4CCA-880B-13537E1944DF.jpeg…]()

**Comment by TripleAx** [comment]
![Uploading 6F296713-9A47-4083-994C-3A7A5B95AC9C.jpeg…]()

**Comment by TripleAx** [comment]
![38366E3E-A898-465C-894C-3B4E796611E4](https://user-images.githubusercontent.com/112257462/187529045-a2d32181-831b-40c8-ab8d-d4b227cad449.jpeg)

**Comment by TripleAx** [comment]
I fixed it with a different way of control

**Comment by jurgenheine** [comment]
For UI you can use Virtual devices and there are flows who can be triggered by both switches or control them

**Comment by TripleAx** [comment]
That’s what i did. Thanks for the reply 👍🏼
