### ISSUE TITLE
Energy monitoring and flow card

### ISSUE THREAD

**Issue by RedBarroth** [jurgenheine/com.tuya.cloud#113]
Just got the smart power plug 16A, my plan was to use it to monitor my water heater but I do not get any energy flow cards and it does not display wattage when I inspect the device in homey. Not sure if I should request it as a feature or report it as a bug since from what I understand it should be possible to read power consumption with the new api and there should be a flow card for it. Maybe just not for my device.

**Comment by jurgenheine** [comment]
The app supports power measure when device and api for device type is supporting power measure. I's working here with my power socket.

**Comment by Norinvstor** [comment]
Hi,
I have added a Wifi socket with power metering in Homey through Tuya Cloud app. But the energy consumption is not updating. I can turn the switch on/off though.

**Comment by jurgenheine** [comment]
One thing to think about, did you select in config tuya cloud all the needed services. One of the services is receiving messages, if not selected you wont get status data. See forum.

**Comment by Norinvstor** [comment]
Hi,
Thank you for the reply. I have filled in everything that is possible to fill inn.
This is from the app in Homey:
![image](https://user-images.githubusercontent.com/50654830/189970445-766aa55e-0120-489b-9b00-e60f2db998bd.png)

**Comment by RedBarroth** [comment]
Could be that I miss a API service, there where alot of them. I did not find any that was  about reciving messages in general, added another one called Power Managment but that did not help.

**Comment by Norinvstor** [comment]
You have the same problem?

**Comment by RedBarroth** [comment]
For me it does not display at all.

**Comment by RedBarroth** [comment]
The Tuya App displays the energy values but in Homey it does not have any indication of measuring energy consumption. Tried to look in the Tuya developer platform but did not get any more insights, it just said that it Repport the values to it self, no information about any Api calls. My guess is that it has implemented a legacy way for communication and that is why it is not displayed by the API.
