### ISSUE TITLE
Tuya curtain(motor)

### ISSUE THREAD

**Issue by AdHoofs** [jurgenheine/com.tuya.cloud#115]
I use Tuya-cloud for many Tuya (Smart Life) products, also for controlling curtainmotors.
Using Smart Life I can control every curtain, but using Homey (Tuya Cloud) it only works with one, which I bougt elsewhere.
Homey excepts all curtainmotors as controllable, but the four coming from SkyLeds don't react on the on/off-commands.
Any idea how to solve this?

**Comment by jurgenheine** [comment]
Are they calibrated to use position, is firmware up to date? Only position is currently supported. If calibration is not possible, you have to use raw flows or scenes for now, when desired with a virtual device.
