### ISSUE TITLE
How to get rid of old API?  I have tried almost a week :(

### ISSUE THREAD

**Issue by ccc19155** [jurgenheine/com.tuya.cloud#116]
![2022-09-13 14 24 03](https://user-images.githubusercontent.com/99755809/189901954-4e58325e-4daf-44e9-a657-42b9f5924972.jpg)
![2022-09-13 14 23 41](https://user-images.githubusercontent.com/99755809/189901957-4661c6b1-8d4d-48b8-9074-3211a59297bb.jpg)
![2022-09-13 14 23 33](https://user-images.githubusercontent.com/99755809/189901960-6c30f765-485b-4513-843d-bb25c16259cf.jpg)
![2022-09-13 14 25 18](https://user-images.githubusercontent.com/99755809/189901961-f4d8641e-8094-44d4-a25e-d8aa6258b2d1.jpg)
![2022-09-13 14 24 25](https://user-images.githubusercontent.com/99755809/189901965-92442aaf-6693-43e6-a30e-19e5d037ef22.jpg)

**Comment by jurgenheine** [comment]
very simple, as stated in comunity forum in bold, set desired api to "**official**" only instead of "**leagacy** and official". Please go to forum if you need configuration help.

**Comment by ccc19155** [comment]
Of course i tried that too, as describet in comunity forum.

![2022-09-13 19 22 33](https://user-images.githubusercontent.com/99755809/189968027-541f6385-8bbf-42af-94a1-52a496b4085b.jpg)
