### ISSUE TITLE
Official api access id?

### ISSUE THREAD

**Issue by eddiex666** [jurgenheine/com.tuya.cloud#118]
Getting this error…
Tryed creating new user…
Trying access secret/id from cloud app

ideas?

![FD421FB9-CCB8-4E69-B52E-C63BC89F61F1](https://user-images.githubusercontent.com/12399173/191019677-9c2e0f24-4b94-432c-9190-fffb64da0907.jpeg)

**Comment by jurgenheine** [comment]
https://community.homey.app/t/app-pro-tuya-cloud/21313
