### ISSUE TITLE
Hihome smart plug functions in Homey but no energy reading

### ISSUE THREAD

**Issue by EnochHa** [jurgenheine/com.tuya.cloud#119]
Dear Jurgen Heine,

Just installed three Hihome smart wall plugs which function in the Tuya Smart app including energy metering. In Homey they function as well, but no energy metering. I use the latest app version and drivers including the official api only. 
I asked Robbshop: they had the same experience and suggested to contact you. 
so could you tell me, do I do something wrong or is this energy function not yet available?
Kind regards
Ed Hartman

Robbshop:
Antw: Hihome Wifi Smart Plug 3.680 Watt Met Energiemeting
Goedemiddag,
We hebben de setup intern nagebouwd en hebben inderdaad hetzelfde probleem, ik raad aan om met Jurgen Heine contact op te nemen.
Mijn mail:
Ik heb een probleem met deze stekker. In de Tuya app kan ik het stroomverbruik wel zien maar niet in de Homey Pro. 
Doe ik iets fout, of werkt het gewoon (nog) niet?

**Comment by jurgenheine** [comment]
Sorry, maar helaas kan ik hier niets aan doen. Als het verbruik (wattage, dus niet stroom) door gegeven wordt, dan zal deze gebruikt worden in Homey. Alleen wordt dit op een of andere manier niet voor elk apparaat door gegeven. Alleen Tuya kan hier antwoord op geven.  Zie ook mijn opmerkingen in Homey forum: https://community.homey.app/t/app-pro-tuya-cloud/21313/1066
