### ISSUE TITLE
Switches not detected

### ISSUE THREAD

**Issue by afca1988** [jurgenheine/com.tuya.cloud#12]
Added two new switches to the Smart Life app. I am logged in and they work great within the Smart Life app. But trying to add them to Homey trough Tuya Cloud (after configuring app and login) keep returning the message: No new devices detected.

Don't know what is going wrong here.

**Comment by tohmc** [comment]
I have the same issue.
Any ideas?

Regards

**Comment by jurgenheine** [comment]
Unless there is new type for switches, it should work. Did you use correct business?  Can you create a report?

**Comment by tohmc** [comment]
Hi,

I created a report via homey

13612288-fe09-4436-8a9e-8b6ae93a2311

**Comment by jurgenheine** [comment]
Found the report. Only a scene is in API discover call.  See below:
`{	"payload": {
		"devices": [
			{
				"data": {},
				"name": "Falls RGB Smart Plug 2 Led Name : ON, \\\"RGB Smart Plug 2\\\" Led Name:ON...",
				"id": "removed",
				"dev_type": "scene",
				"ha_type": "scene"
			}
		],
		"scenes": []
	},
	"header": {
		"code": "SUCCESS",
		"payloadVersion": 1
	}
}`

**Comment by afca1988** [comment]
> Unless there is new type for switches, it should work. Did you use correct business? Can you create a report?

Tried both the Smart Life app as the Tuya app. I can add the switches in both apps successfully. But within the homey app it stops :(

**Comment by tohmc** [comment]
> Found the report. Only a scene is in API discover call. See below:
> `{ "payload": { "devices": [ { "data": {}, "name": "Falls RGB Smart Plug 2 Led Name : ON, \\\"RGB Smart Plug 2\\\" Led Name:ON...", "id": "removed", "dev_type": "scene", "ha_type": "scene" } ], "scenes": [] }, "header": { "code": "SUCCESS", "payloadVersion": 1 } }`

So what is the problem with it?
It is a device (socket with Rgb led)
And it have a scene.

**Comment by tohmc** [comment]
> Found the report. Only a scene is in API discover call. See below:
> `{ "payload": { "devices": [ { "data": {}, "name": "Falls RGB Smart Plug 2 Led Name : ON, \\\"RGB Smart Plug 2\\\" Led Name:ON...", "id": "removed", "dev_type": "scene", "ha_type": "scene" } ], "scenes": [] }, "header": { "code": "SUCCESS", "payloadVersion": 1 } }`

Here is another report after new smartlife plug was installed.

849ddf10-b38a-4348-b08b-a1e080164902

Deleted the old scene; deleted the old plug.

Put in new plug and new scene.
Tried also with tuya as business but it don’t work.

**Comment by tohmc** [comment]
Any news?

**Comment by jurgenheine** [comment]
Only scene is shown, just like first, but name is different. The device is again not shown in the message. So the device is not supported by the API this app is using, so unfortunately it is not possible to support this device.

**Comment by robvos** [comment]
Did you restart the tuya cloud app in homey? This helped with me.

**Comment by tohmc** [comment]
Yes i did but it did not help

**Comment by Dikootje** [comment]
I'm trying to develop Cover support for this app. I ran into a issue with discovery which could maybe be the cause of these issues as well: 

`msg: 'you can discovery once in 300 seconds',`

My workaround for local development at the moment is to set `REFRESHTIME` to an hour in cloudtuya.js. Even then I still have to wait for 5 minutes after the app has loaded on Homey before I can find my device.

**Comment by jurgenheine** [comment]
The message is new for me, it was possible to discover with shorter intervals. So they have changed this, it could explain some issues.

**Comment by jurgenheine** [comment]
Implemented new API
