### ISSUE TITLE
Missing compability listener onoff

### ISSUE THREAD

**Issue by Squid84** [jurgenheine/com.tuya.cloud#121]
I get Avivs issue since this morning. anyone else have the same issue? 

0c224a22-f88c-459e-8c97-a54302faf0c3

**Comment by jurgenheine** [comment]
[log] 2022-10-04 07:52:43 [TuyaCloudApp] TuyaOpenAPI response: {"code":28841002,"msg":"No permissions. Your subscription to cloud development plan has expired.","success":false,"t":1664869963488,"tid":"873453a643b911ed9f9b22dacb9008b9"} path = /v1.0/iot-01/associated-users/devices
