### ISSUE TITLE
Missing Capability Listener

### ISSUE THREAD

**Issue by waynelaagewaard1** [jurgenheine/com.tuya.cloud#122]
Hi

I had to restore my homey today and suddenly i get the message Missing Capability Listener: onOff when I try to turn a plug (Tuya) on.

When i try to turn on a tuya light i get no response

When i use the tuya app i have no issues

I am on the official API
Homey app 6.11.5.956
Tuya app 1.1.12

I tried: different wifi channels…
Restore and reboot

Seams like i have no connection to tuya at all

**Comment by Squid84** [comment]
Same issue here. Trying to uninstall. Then reinstall.

**Comment by jurgenheine** [comment]
See #121
