### ISSUE TITLE
Tuya Cloud stops working

### ISSUE THREAD

**Issue by tuomaskilpimaa** [jurgenheine/com.tuya.cloud#127]
App doesn't work anymore. Nothing change in my tuya developer project, smartlife app or homey. But I can't add anymore new devices. Homey just inform that "Please configure the app first." Is there some change happened in Tuya?

**Comment by jurgenheine** [comment]
Depends on many factors. If you still use old depricated api, switch to new api. If you use new api, did you renew the subscription?
Go to community forum for help if needed.
