### ISSUE TITLE
Tuya cloud API not working anymore with Homey

### ISSUE THREAD

**Issue by B3rt** [jurgenheine/com.tuya.cloud#129]
Since today the api connection is not working anymore (homey firmware was yesterday updated).
No devices respond, there is no error.
When using tuya app is works fine, using tuya cloud api via Home Assistant it also works fine, via Homey it stopped working.

When you go into settings and try to save it an error appears:
“Error: Error: Code: 2406; msg: skill id invalid”

Log/message/diagnostic ID: 6658ae7d-98a7-4af7-8749-d78b3a0cba82

**Comment by Genghes** [comment]
This error is mentioned here:
[https://community.homey.app/t/app-pro-tuya-cloud/21313](https://community.homey.app/t/app-pro-tuya-cloud/21313)

Also check if the IoT service has expired. (Also explained on that site)

**Comment by jurgenheine** [comment]
I will close this issue, the solution is found by yourself and posted in Community forum.
