### ISSUE TITLE
Switch with energy monitoring

### ISSUE THREAD

**Issue by pahen** [jurgenheine/com.tuya.cloud#13]
Hi,

Thanks for this app!

I can switch on/off my switch but would love to get energy monitoring working too. Have you got this working for any switch? Or is it planned for the future?

I have this switch https://www.deltaco.se/produkter/deltaco/smart-home/grenuttag/SH-P02 and I'm running the TuyaSmart app on my mobile.

![IMG_2753](https://user-images.githubusercontent.com/353888/88664705-c0402300-d0dd-11ea-85b2-11497ea61308.PNG)

![IMG_2754](https://user-images.githubusercontent.com/353888/88664714-c46c4080-d0dd-11ea-86a2-a0084b58a88d.PNG)

**Comment by jurgenheine** [comment]
This is not possible at the moment, see #9

**Comment by jurgenheine** [comment]
With new API it's possible. Should be implemented in next Test version
