### ISSUE TITLE
New API doesn’t work

### ISSUE THREAD

**Issue by Tom7822** [jurgenheine/com.tuya.cloud#136]
Hi,
I follow instructions to create project, link app tuya and obtain API access but it dosen’t work. 
Yet in tuya app configuration for Homey no code error (so it’s seems to be right code) but i can’t add a device, so i don’t know why it doesn’t work. 
Thanks

**Comment by jurgenheine** [comment]
[https://github.com/jurgenheine/com.tuya.cloud, first ](https://github.com/jurgenheine/com.tuya.cloud#readme), Read first chapter.
