### ISSUE TITLE
Tuya app not working anymore

### ISSUE THREAD

**Issue by Harmbe** [jurgenheine/com.tuya.cloud#138]
Hi Jürgen,

the Tuya cloud app used to work fine but since a couple of days it won’t operate with my devices anymore.
Lightbulbs don’t give error messages but won’t switch on or off anymore. Switches give error message “ Missing Capability Listener: onOff ”.  When trying to add a new device the app tells me to configure the app first. I tried to use an earlier homey backup but no success either.

many suggestions what’s going on?

**Comment by DPANET** [comment]
Same issue here I thought it was a misconfiguration now the whole app is not able to add new devices and existing devices get missing capability issues.

**Comment by Spooren** [comment]
Same problem here. It worked with Homey until 2 days ago. I followed all the steps to create a Tuya cloud API account and it worden okay. But it stopped 2 days ago. Can not find a solution now. :-(

**Comment by Harmbe** [comment]
Hi all,

I found the solution. Subscription on Tuya iot platform (tuya core) expires. After extending everything works fine again. Don’t forget to save app configuration in Homey again and restart the app.

**Comment by DPANET** [comment]
Can you explain how Tuya account is renewed, I could not find this option

**Comment by Spooren** [comment]
Log in to https://iot.tuya.com/
Cloud > Cloud Services
IoT Core > click on alert > view exeption status
Click Extend Subscriprion
Fill in the form > submit
