### ISSUE TITLE
Connect Tuya IR remote control with Homey

### ISSUE THREAD

**Issue by paececu** [jurgenheine/com.tuya.cloud#139]
Hello,

I have a few tuya devices and four of them are IR remote control from Tuya. [IR remote](https://expo.tuya.com/product/686103l)
I'm currently using the smart life app and I'm automating my home a little bit and I would like to use Homey to connect all my devices.
I tried to use tuya IOT to connect to my devices and I can see them there already but regarding integration with Homey I find out that the existing applications from Tuya are not compatible with these equipment.
[Tuya cloud app](https://homey.app/en-us/app/com.tuya.cloud/Tuya-cloud/)
[Tuya app](https://homey.app/en-us/app/nl.rebtor.tuya/Tuya/)

Does anyone knows if there is a plan to integrate these devices too?

Any support will be warmly welcome.
Thank you

**Comment by jurgenheine** [comment]
There are raw flows and scenes, if those don't work with IR devices, then it's not possible. Please go to community forum if you need further assistants.
