### ISSUE TITLE
Trouble setting dim (and color)

### ISSUE THREAD

**Issue by badduiker** [jurgenheine/com.tuya.cloud#14]
We recently bought several (different) LED lamps and registered them in Tuya Cloud App. No problems there: color, dim, etc. can be set just fine. Using your App, connected them in Homey: 3 issues apear: 1. Colors cannot be set, 2. dim to 100% gives much less light then 100% should be (as showing 100% in Tuya App) and 3. dim to 0% does not seem to work at all? Any clues?

**Comment by jurgenheine** [comment]
This are known errors and can't be solved at the moment. See #11 and #4

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details
