### ISSUE TITLE
3rd time in a few months i get the same error and need to create new acoount. Missing capability listener onoff.

### ISSUE THREAD

**Issue by Squid84** [jurgenheine/com.tuya.cloud#141]

**Comment by Squid84** [comment]
I need to register a new account on Tuya page once a month.

**Comment by jurgenheine** [comment]
[https://github.com/jurgenheine/com.tuya.cloud, first ](https://github.com/jurgenheine/com.tuya.cloud#readme), Read first chapter. It's nothing I can do anything about.
