### ISSUE TITLE
No scenes after update 1.1.21

### ISSUE THREAD

**Issue by llentjes** [jurgenheine/com.tuya.cloud#143]
After update to version 1.1.21 I cannot use scenes anymore.
When using the button ` reload scenes` there is no error, but in the flowchart ' execute scene' the selection list remains empty.
After removing a device and trying to add it again there is a message: Please configure the app first
removing the app and reinstalling doesn't solve the issue either.

Please help.

**Comment by jurgenheine** [comment]
https://github.com/jurgenheine/com.tuya.cloud/tree/master, fisrt part
