### ISSUE TITLE
Tuya cloud app not working after update

### ISSUE THREAD

**Issue by fvhuizen** [jurgenheine/com.tuya.cloud#144]
Since the update V1.1.21 from two days ago. The app can’t manage any Tuya device anymore. 
I checked not.tuya.com but all devices are online and if I want to switch something with the SmartLife app everything works.
If I manually try to switch something in Homey I got the error: missing capability listener on/off

diagnostic report
f26a7c8a-ded8-4c1c-85c9-6226dcf6ca67

**Comment by fvhuizen** [comment]
Hmmmmm it was the subscription. I hope there will be a solution in future to avoid such issues

**Comment by jurgenheine** [comment]
This should be asked on the forum, and it's the choice of Tuya. I can't do anything about.
