### ISSUE TITLE
Tuya stopped working - message: please configure the app first

### ISSUE THREAD

**Issue by sdspieg3** [jurgenheine/com.tuya.cloud#149]
I have 2 lamps registered in Tuya app. Yesterday evening they worked fine with homey.
Normally when I put on the alarm, I switch the lamps off, but this morning I saw they were still on. So tried to switch them manually off via homey, but it wasn't working anymore.

I removed my lamps in homey and tried to add them again, but i got the message please configure the app first
I then removed the app once from homey and re-installed, but when trying to add the lamps again, I got the same message.

Cloud project is defined, app is configured and everything was working before today without any problems.

Thanks for watching into this

Diagnostic report id: AB845E

**Comment by sdspieg3** [comment]
![image](https://user-images.githubusercontent.com/120310331/206901527-af8394ba-9d21-46be-bb45-5c345a1188b9.png)


Both lamps are online in Tuya

**Comment by jurgenheine** [comment]
https://github.com/jurgenheine/com.tuya.cloud
