### ISSUE TITLE
Missing Capability Listener: onOff

### ISSUE THREAD

**Issue by fredrikarstrom** [jurgenheine/com.tuya.cloud#158]
I get the message Missing Capability Listener: onOff when I try to turn a plug (Tuya) on in Homey app.

When I try to turn on a tuya socket I get no response. When I use the tuya app I have no issues. This error has occured since the last week. Before it worked perfect.

**Comment by adriaan66** [comment]
Same problems here since today (13-01) i hope there is asap a fix..

**Comment by Anteboyan** [comment]
Same problem here since yesterday (14-01).

**Comment by adriaan66** [comment]
I have a work arround, i change the app to "Use legacy and official" instead "Use official only", now the message is gone and the sockets are working from the Homey App. I hope i can switch soo to "Use legacy and official" so i don't receive the message, i using the old deprecated API anymore :-)

**Comment by KvDaalen** [comment]
Have the same issue, workaround is not working.

**Comment by KvDaalen** [comment]
@fredrikarstrom did you manage to get it up and running again?

**Comment by jurgenheine** [comment]
https://github.com/jurgenheine/com.tuya.cloud
