### ISSUE TITLE
Is bluetooth compatible? tuya BLE spotlights

### ISSUE THREAD

**Issue by uffe6** [jurgenheine/com.tuya.cloud#160]
Perhaps this is a noob question. However i can't get my head around it.

I have a couple of malmbergs BLE spotlight. I control these with the tuya mobile app (IOS)

Have installed the tuya cloud app, and follow the tutorials. everything works. I can add the lights in homey etc.

Hower. from the tuya app. I'm controlling the light directly from my phone via bluetooth.

Is it even possible to control them via Homey? I mean i don't understand how Homey should understand the BLE protocl etc. Or I'm i missing something? Anyway, the light does not work via homey despite that they have been added and everything looks good in the app (dimmer and colur etc) However nothing happens.

Is it possible to control BLE light via homey thrue this cloud solution? And if so, what am I doing wrong? How should Homey understand the BLE protocol since the setup is done between the phone and the lights.

Sorry for all noob questions....

**Comment by jurgenheine** [comment]
This cloud only and not bluetooth. I am also stopped with development, I moved to Home assistant. Maybe as an other developer takes over.
