### ISSUE TITLE
Scene not detected 

### ISSUE THREAD

**Issue by biggy5252** [jurgenheine/com.tuya.cloud#18]
Hello. 

Previously I was able to trigger a scene/mood inside a flow using the Tuya Cloud app. 

Since the last update I think , I can no longer see the scenes/mood anymore. The previously configured ones are triggering fine, but when adding a new one, I don’t see it picking up the created scenes in SmartLife app. 

Is this a bug or do i need to change something. 

Thanks

**Comment by jurgenheine** [comment]
This was indeed a bug and is solved with PR #17  by p. keuter. This evening I will deploy the fix to the [test channel](https://homey.app/nl-nl/app/com.tuya.cloud/Tuya-cloud/test).
