### ISSUE TITLE
Login problems (accesstoken)

### ISSUE THREAD

**Issue by DieJan** [jurgenheine/com.tuya.cloud#2]
Whenever I try to log in from the Homey app settings, I get an error message saying:

Error: Get accesstoken failed. Username or password error!

I tried everything. Both emailaddress and telephonenumber, changed my password, checked the country code, and also tried both businesses (smart_life and tuya). Every time I keep getting this error. I see in the Chrome inspection window that all my settings are stored correctly on Homey, but I keep getting the error.

Also rebooted Homey, and the app a few times.

**Comment by jurgenheine** [comment]
Someone reported this error also on homey community. The solution was to uninstall the app and install again, but I am still curious where this error comes from and want to solve it. The error is comming directly from Tuya when this app signs in to the cloud. You could try to change the country code to a country close to you, the country code is only used to determine region and not for authentication. Can you share screenshots of Tuya/Smart life android app?

**Comment by steffjenl** [comment]
I have the same error, in the homey settings i have put countrycode 31.

username: stephan@.........

> {"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}

![IMG_2181](https://user-images.githubusercontent.com/2580852/87759345-74a09600-c80e-11ea-88ac-40487bde4a7e.PNG)
![IMG_2180](https://user-images.githubusercontent.com/2580852/87759350-75d1c300-c80e-11ea-9844-d63bd6514e11.PNG)

**Comment by baptistepho** [comment]
Hello, I have the same problem. Any idea how I can fix it?

**Comment by jurgenheine** [comment]
Those screenshots are not from tuya app settings page but for Iphone I think. Have you tried to reinstall the Tuya app as I suggested?

**Comment by steffjenl** [comment]
@jurgenheine where can i find the app? from Homey?
![image](https://user-images.githubusercontent.com/2580852/87849605-32e51d80-c8ea-11ea-92d1-f3e75356af59.png)

**Comment by steffjenl** [comment]
When you created an account with your Apple ID, and changed your username later it doesn't work! When you create an new account it works with the store app. 

The app on github is broken? you can't pair devices anymore?
