### ISSUE TITLE
Can't manage Gosund & Meross power outlets with the Tuya App in Homey

### ISSUE THREAD

**Issue by adriaan66** [jurgenheine/com.tuya.cloud#20]
Can't manage Gosund & Meross power outlets with the Tuya App in Homey

**Comment by jurgenheine** [comment]
I need a diagnostic report to look why it's not working, this report shows result from Tuya. Post the generated id here afterwards.

**Comment by adriaan66** [comment]
> 
> 
> I need a diagnostic report to look why it's not working, this report shows result from Tuya. Post the generated id here afterwards.

I have tested something and now it works.. (with Gosund) i don't have tried Meross again, i will do that within a few days.
A few days ago theire was a problem with AWS, maybe that was the reason that it doesn't work.

Regards,
Adriaan

**Comment by jurgenheine** [comment]
Good to hear it works now, I close the issue for now
