### ISSUE TITLE
Smart Life App: adding to Homey results in no devices found

### ISSUE THREAD

**Issue by m3ngi3** [jurgenheine/com.tuya.cloud#22]
So the instructions seem pretty straight forward:

1) I have the Smart Life mobile app in Iphone working for quite some time now so already working with a Smart Life / Tuya account
2) Install Tuya Cloud App on Homey Device
3) Configure Tuya Cloud App in Homey App
4) Reconnect says successful so assuming that Tuya cloud settings are accepted & Save settings
5) Add device using suggestion of Tuya Cloud 
6) Select device type = Switch --> No devices found / Geen nieuwe apparaten gevonden

Missing anything?

**Comment by jurgenheine** [comment]
I need a diagnostic report to look why it's not working, this report shows result from Tuya. Post the generated id here afterwards.

**Comment by m3ngi3** [comment]
Like this?
![E7A49280-F6DF-45EE-9C62-C803D5605B4F](https://user-images.githubusercontent.com/47530580/100469840-565d7780-30d7-11eb-9817-f6363afcf9bc.jpeg)

5079f05c-847c-46bb-a8fa-6ce85976c553

**Comment by jurgenheine** [comment]
No, this is app settings page. You have to make a diagnostics report. It's on app details and then gear icon( right top)

**Comment by jurgenheine** [comment]
I seen now guid in bottom, that is what I needed.

**Comment by jurgenheine** [comment]
Found your diagnostic report, the devices are available to the app. So the credentials should be correct, otherwise we shouldn't see the device, but I see a errors about "Get accesstoken failed. Username or password error!". I have to investigate this. Also Tuya has changed the polling frequenty to 10 minutes and for authentication to 1 minute

**Comment by m3ngi3** [comment]
Thanks for checking 🙏🏼

Based on your info I uninstalled the app, reinstalled, added credentials, saved, reconnect and within 1 mins tried to add Switch —> very briefly a different red error about network error and then back to same behavior: 95b46add-5832-4387-aa11-cc2ed37bdc95

**Comment by jurgenheine** [comment]
You can try test version, I just saw that you are on stable. I solved there somthing simular, see also community forum.

**Comment by m3ngi3** [comment]
No luck on iPhone... will try also try web app on laptop... test version cannot send diagnostic report?

**Comment by jurgenheine** [comment]
Test apps can send diagnostics

**Comment by m3ngi3** [comment]
I see: longer text is needed before button works
fdbb7402-1f98-4dfd-a15a-c23a5b92814e

**Comment by m3ngi3** [comment]
Installed Homey on iPad with Smart Life not connected... now devices were added fff8b89a-92de-4e39-8799-4b413b4eced4

**Comment by jurgenheine** [comment]
Good to hear you can add devices now.
