### ISSUE TITLE
Blitzwolf products

### ISSUE THREAD

**Issue by kohler1979** [jurgenheine/com.tuya.cloud#26]
Hello . Thanks for good app.  Do u have any plans of adding support for more blitzwolf products? They join with the smartlife and tuya cloud really good   i even found some plugs in homey thrue the tuya cloud app . Regards magnus

**Comment by jurgenheine** [comment]
The app doesn't support brand products directly. Only the devices which are supported by the Tuya API are supported. This unfortunality is a short list of device types. Only Tuya determines which devices and types can be supported. See the readme for more info.
