### ISSUE TITLE
Can't select a tap-to-run with "trigger a scene card" 

### ISSUE THREAD

**Issue by PeterKawa** [jurgenheine/com.tuya.cloud#29]
Tuya Cloud app v.0.014 (experimental)
Homey v5.0.2

Hi Jurgen,

A little bug (I hope):
I tried to add a tap-to-run scene (from my phone's Tuya Smart app) on Homey, with the "trigger a scene" card.
The selection list is empty, while having lots of tap-to-run scenes present.

I reconnected the Tuya connection.

I did not create a new scene, I was just fiddling around.
The existing flows with a 'trigger a scene" card work fine, the corresponding tap-to-run scenes are being triggered.

Thanks, and if you need additional info, or testing, just let me know 

Peter

**Comment by jurgenheine** [comment]
You are correct about the bug, this is fixed in v0.0.15 which is now in test.
