### ISSUE TITLE
Can not add light bulb

### ISSUE THREAD

**Issue by henrikhenkejohansson** [jurgenheine/com.tuya.cloud#30]
Hi, I just installed the TuyaSmart iOS app and added my first lightbulb to it. Now I was going to add it to Homey, installed this tuya app to Homey but can not add any light bulb. I only get an error message than no bulb was found. What can be the reason for this?

**Comment by jurgenheine** [comment]
Be sure to use correct credentials, most problems are incorrect login credentials. ALso not all devices are supported, wifi lights are supported for on/off and some with more functions. See also forum https://community.athom.com/t/app-tuya-cloud/21313
