### ISSUE TITLE
Tuya only works after a daily restart

### ISSUE THREAD

**Issue by Martinbugel** [jurgenheine/com.tuya.cloud#32]
Hello, 

I have a problem with the app. It needs a restart every day. Can you fix this?

Thanks.
Regards

**Comment by jurgenheine** [comment]
I need more info to fix, you have to make a app diagnostics report ( not global diagnostics report) en report guid here. I also want to know what the memory foot print is at moment of no response. You can see this with insights and make a screenshot.

**Comment by michaelsing** [comment]
3256D0 guid

**Comment by michaelsing** [comment]
![image](https://user-images.githubusercontent.com/9927356/117243926-64f34c00-ae38-11eb-8a89-e150c6552442.png)

**Comment by michaelsing** [comment]
![image](https://user-images.githubusercontent.com/9927356/117244058-a71c8d80-ae38-11eb-8884-51182a03d345.png)

**Comment by michaelsing** [comment]
![image](https://user-images.githubusercontent.com/9927356/117244096-bbf92100-ae38-11eb-8750-9005b1fd2777.png)

**Comment by michaelsing** [comment]
App diagnostic: ae814a4c-9e3d-405b-97b3-b492075747e8

**Comment by jurgenheine** [comment]
The cpu and memory looking. There is an error which indicating there is something wrong with your "Tuinlicht". It's sending values out of range, see error log below. Best thing is to remove the device and try to pair the device again.

---- stdout ----
2021-05-06 09:30:04 [log] [TuyaCloudApp] Start connection to cloud.
Discover devices
2021-05-06 09:30:04 [log] [TuyaCloudApp] Tuya cloud App has been initialized
2021-05-06 09:30:04 [log] [ManagerDrivers] [cover] Tuya Cover Driver has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [light] Tuya Light Driver has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [light] [0] Tuya Light Tuindeur has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [light] [1] Tuya Light Tuinlicht has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [light] [2] Tuya Light Kookplaat lamp has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [switch] Tuya Switch Driver has been initialized
2021-05-06 09:30:05 [log] [ManagerDrivers] [switch] [0] Tuya switch  Buitenstroom wcd has been initialized
{"access_token":"xxxx","refresh_token":"xxx","token_type":"bearer","expires_in":864000}
request input: {"url":"https://px1.tuyaeu.com/homeassistant/skill","method":"POST","json":{"header":{"name":"Discovery","namespace":"discovery","payloadVersion":1},"payload":{"accessToken":"xxxx"}}}
{
  payload: {
    devices: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    scenes: []
  },
  header: { code: 'SUCCESS', payloadVersion: 1 }
}
request output: {"payload":{"devices":[{"data":{"brightness":"370","online":true,"state":"false"},"name":"dimmen","icon":"https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/158754167737006edd612.jpg","id":"xxx","dev_type":"light","ha_type":"light"},{"data":{"online":false,"state":false},"name":"Smart Plug-EU","icon":"https://images.tuyaeu.com/smart/icon/ay1533863461091cyfW7/1573001807025a2792871.png","id":"xxxxx","dev_type":"switch","ha_type":"switch"},{"data":{"brightness":"34","online":true,"state":"false"},"name":"Kookplaat lamp","icon":"https://images.tuyaeu.com/smart/icon/15548239257ypxzpm4qgx_0.jpg","id":"xxxxx","dev_type":"light","ha_type":"light"},{"data":{"brightness":"94","online":true,"state":"false","color_temp":10000},"name":"LED SMART","icon":"https://images.tuyaeu.com/smart/icon/ay1542197947067LbyQC/1575592762eca3bc63a65.png","id":"xxxxx","dev_type":"light","ha_type":"light"},{"data":{},"name":"Zonsondergang","id":"xxxxxx","dev_type":"scene","ha_type":"scene"},{"data":{},"name":"Zon opkomst","id":"xxxxxx","dev_type":"scene","ha_type":"scene"}],"scenes":[]},"header":{"code":"SUCCESS","payloadVersion":1}}
Get device for: xxxxx
Device found
try update data
update device: {"brightness":"370","online":true,"state":"false"}
2021-05-06 09:30:05 [log] [TuyaCloudApp] dimmen updated
Get device for: xxxxx
Device found
try update data
update device: {"online":false,"state":false}
2021-05-06 09:30:05 [log] [TuyaCloudApp] Smart Plug-EU updated
Get device for: xxxxxx
Device found
try update data
update device: {"brightness":"34","online":true,"state":"false"}
2021-05-06 09:30:05 [log] [TuyaCloudApp] Kookplaat lamp updated
Get device for: xxxxxx
Device found
try update data
update device: {"brightness":"94","online":true,"state":"false","color_temp":10000}
2021-05-06 09:30:05 [log] [TuyaCloudApp] LED SMART updated
2021-05-06 09:30:05 [log] [TuyaCloudApp] Zonsondergang updated
2021-05-06 09:30:05 [log] [TuyaCloudApp] Zon opkomst updated
2021-05-06 09:30:05 [log] [TuyaCloudApp] Connected to cloud.
set capabilities: {"onoff":false}
request input: {"url":"https://px1.tuyaeu.com/homeassistant/skill","method":"POST","json":{"header":{"name":"turnOnOff","namespace":"control","payloadVersion":1},"payload":{"value":"0","accessToken":"xxxxxxL","devId":"xxxxx"}}}
{ payload: {}, header: { code: 'SUCCESS', payloadVersion: 1 } }
request output: {"payload":{},"header":{"code":"SUCCESS","payloadVersion":1}}

---- stderr ----
2021-05-06 09:30:05 [err] [ManagerDrivers] [light] [1] Error: out_of_range
    at Remote Process

**Comment by jurgenheine** [comment]
New API implemented. Maybe solves this issue
