### ISSUE TITLE
Cant add devices - bulb and socket

### ISSUE THREAD

**Issue by ThomasLagerstedt** [jurgenheine/com.tuya.cloud#33]
Hi, seems like I’m entered the right login criteria for the Tuya Cloud app in Homey but when i try to add a device nothing is happening. 

In my SmartLife app I have a couple of these devices.

https://www.webhallen.com/se/product/296331-Nedis-WiFi-Smart-LED-lampa-125-mm-Filament-Amber-E27

https://www.webhallen.com/se/product/306173-Nedis-Wi-Fi-Smart-Utomhus-Plug-IP44-Energimatning-16A

**Comment by jurgenheine** [comment]
There is now new API support, probably solves problems
