### ISSUE TITLE
Slow reaction

### ISSUE THREAD

**Issue by eeckelaertyannick** [jurgenheine/com.tuya.cloud#35]
Hi,

i have slow réaction wit thé Lidl wifi lamps.
If i use the tuya app. Thé react in à second.
Buth with Homey ore wit zigbee devices, end flow’s the are really slow. Is there a sollution?

thx!

**Comment by jurgenheine** [comment]
Its a app which connects with a Tuya cloud API, so internet connection is important. The app sends the commands directly to the Tuya cloud API, so nothing I can do about this.
