### ISSUE TITLE
Tuya LAN

### ISSUE THREAD

**Issue by ladislavlala** [jurgenheine/com.tuya.cloud#36]
Do you PLEASE plan to implement support for Tuya via LAN at Homey? It takes several seconds to turn on / off Tuya compatible light via Tuya cloud app. which is not ideal :-( THANK you in advance.

**Comment by jurgenheine** [comment]
It's called Tuya cloud, so it connects to Tuya cloud API. For local access you have to use another app, [https://homey.app/nl-nl/app/nl.rebtor.tuya/Tuya/](https://homey.app/nl-nl/app/nl.rebtor.tuya/Tuya/). Combining both is not possible.
