### ISSUE TITLE
Speed of response

### ISSUE THREAD

**Issue by ladislavlala** [jurgenheine/com.tuya.cloud#38]
Hello Jurgen,

I am struggling with the performance of TUYA lights managed via Homey (7.0.1) / Tuya cloud (v0.0.15). 

It takes a while (~ seconds) until lights are switched on / off. Definitely significantly longer compared to HUE etc. Is it because of cloud and there is nothing I can do except changing lights? I spent some time trying to obtain local key, but Tuya app is supporting just a few devices.

Response of light is btw much faster while using Tuya smart app, but I need all devices in Homey because of integration...

Any idea please? I will pay with gold :-)

Kind Regards,
Lada

**Comment by jurgenheine** [comment]
Unfortunality I can't do anything about it. As you already sugested, it's mainly because of cloud. So It's your internet connection or your location. Tuya uses 3 locations (China, Europe and US). The Tuya Android/IOS apps are capable of local access, so they work offline and faster.

**Comment by ladislavlala** [comment]
THANK you very much for the prompt reply. I was not aware that Tuya Android/IOS are capable of local access. 

Do you PLEASE plan to integrate local access anytime soon / at all? It would made my day :-)

Thank you,
Lada

**Comment by jurgenheine** [comment]
There is already other local app, but needs the local keys. Local acces without the keys is not possible. This app uses the cloud api, which uses different keys. Those 2 can't be mixed, already tried.

**Comment by ladislavlala** [comment]
I am aware of other app. Unfortunately only a few devices are supported. Despite I have local keys I am being forced to replace my Tuya lights with something :-(

**Comment by jurgenheine** [comment]
There is now new Cloud API implemented. Maybe it improves the resonse. But internet connection is probably still more likely issue.
