### ISSUE TITLE
Light Errors

### ISSUE THREAD

**Issue by AdyRock** [jurgenheine/com.tuya.cloud#4]
Hi,
I have flood lights connected to tuya and I am not seeing the colour picker, only the white shade.
Running the app from the CLI I see errors pointing to undefined member as there is no data for the colour entry, such as brightness, etc. The information returned from discover devices is:
Discover devices
request input: {"url":"https://px1.tuyaeu.com/homeassistant/skill","method":"POST","json":{"header":{"name":"Discovery","namespace":"discovery","payloadVersion":1},"payload":{"accessToken":"..................................................................."}}}
{ payload: { devices: [ [Object], [Object] ], scenes: [] },
  header: { code: 'SUCCESS', payloadVersion: 1 } }
request output: {"payload":{"devices":[{"data":{"brightness":"1000","color_mode":"colour","online":true,"state":"true","color_temp":1000},"name":"Shed Flood","icon":"https://images.tuyaeu.com/smart/program_category_icon/dj.png","id":".....................................","dev_type":"light","ha_type":"light"},{"data":{"brightness":"1000","color_mode":"colour","online":false,"state":"true","color_temp":36294},"name":"Kitchen Flood","icon":"https://images.tuyaeu.com/smart/program_category_icon/dj.png","id":".............................................","dev_type":"light","ha_type":"light"}],"scenes":[]},"header":{"code":"SUCCESS","payloadVersion":1}}

So colour_mode is being returned as colour but no sign of any colour information. As I'm not sure what is actually expected I don't know if what I seeing is good or bad data.
Also the colour temp for the offline device seems a bit high for the formula used in the app and causes an out of range error.

I'm hope this information helps but if you need anything else then let me know.

Best regards,
Adrian.

(I have replaced ID's with .......)

**Comment by AdyRock** [comment]
From what I can make out by changing settings the tuya app and watching the data coming back to your app, the brightness for white is between 10 - 1000 and the color_temp is between 1000 - 36294 when being received.
When sending the color_temp back the value needs to be between 1000 and 10000 to get the tuya app to display the correct value.

**Comment by jurgenheine** [comment]
The mode is returning color, but actual color information is missing. The values are different then for my lights, I have to look futher into this.

**Comment by jurgenheine** [comment]
The error for brightness should be solved with version 0.0.5. The color information is still missing in Tuya API response, so can't be used.

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details

**Comment by AdyRock** [comment]
Yep, switching to the new API fixes the issue.
Thank you for your perseverance.
