### ISSUE TITLE
Slow app response

### ISSUE THREAD

**Issue by eeckelaertyannick** [jurgenheine/com.tuya.cloud#41]
Hi Jurgen,

Tuya app respond is slow whit Homey if I use the original tuya app it works great. Got a response from somwone one the Homey Facebook platform

FYI:

The delay from Homey is due to the Tuya API used.
Doesn't depend on your WiFi.
Many manufacturers put limits (number of times or speed) on their APIs, they hope that you will use their products, which are then fast ;-)

In Home Assistant, the Tuya v2 integration (from Tuya itself) devices respond almost faster than on the Tuya phone app.
Do you still get it?

-----------

Maybe you can do something about this? If it works better in home assistant schould this not be possible for Homey. Maybe ask tuya Devolper team? In Homey we are all potential tuya device users this schould Maybe motivate the to build it also for Homey en faster more devices or let you build it? 

Thx in advance!

**Comment by jurgenheine** [comment]
Sending commands should be instant, but is certainly depended on you internet connection. Slow connection( a high ping to Tuya API) give slow response. But the API call for getting status of a device is limited by Tuya once in 10 minutes. 

Tuya has indeed an other API. This API was first only for business and you had to pay for access. Recently They changed the terms of use, now you can get a free subscription with limited calls for a year. Again you have to pay if the number of call are increasing past a limit( I don't know the actual limit). Also this API differs a lot from the one currently used by this app. So switching to other API means complete rewrite of this app.

**Comment by eeckelaertyannick** [comment]
Ok jurgen, I hope maybe further support or enhancements wil change this an make it quicker. I also want to make them local because this wil make the response quicker en let's me use them also when there is no cloud connection ore further support

**Comment by jurgenheine** [comment]
New API implemented
