### ISSUE TITLE
Action Color lamp no Color

### ISSUE THREAD

**Issue by eeckelaertyannick** [jurgenheine/com.tuya.cloud#42]
Heu jurgen, have one issue I have 1 action lamp in the cloud en can change collors buth not whit Homey. Can u advice?

Many thx!

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details

**Comment by Plantje1978** [comment]
The Homey forum?

**Comment by jurgenheine** [comment]
Yes: https://community.homey.app/t/app-pro-tuya-cloud/21313

**Comment by jurgenheine** [comment]
Probably solved with new API implementation

**Comment by Plantje1978** [comment]
Yes, it is fixed. Sorry for not reaching out and letting you know
