### ISSUE TITLE
Dim niveau tuya lights

### ISSUE THREAD

**Issue by eeckelaertyannick** [jurgenheine/com.tuya.cloud#44]
Hey Jurgen,

If I dim the lamps to 1% the are stil 4% in the tuya app. There a bit completely at minimum dim level. End would it be possible tu activate dim niveau for a room? Ore make lamps in groups? 

Thx!

**Comment by eeckelaertyannick** [comment]
The dimm level difference i do not understand. Can you explaine lite more?

**Comment by jurgenheine** [comment]
smallest value is 0.01 * 255=  rounded to 3

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details
