### ISSUE TITLE
Addition of extension

### ISSUE THREAD

**Issue by tobi8868** [jurgenheine/com.tuya.cloud#49]
Hello.
I use Google Translate as I do not know English.
I hope you understand my question anyway.
I would like to add my extension, which has 4 connectors, and 3 USB connectors.
I just have not made it work yet.
Is it possible it will be possible in the future?
Thanks in advance.
Sincerely.
Tobias.

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details
