### ISSUE TITLE
Light in Tuya is not controllable in Homey

### ISSUE THREAD

**Issue by AndreLion** [jurgenheine/com.tuya.cloud#53]
I connected a DELTACO Smart Light in Tuya smart app, and it works as  expected 👍
![image](https://user-images.githubusercontent.com/85134/147756675-a427d1ea-5e3b-4cd8-b4af-b5c43439ec5e.jpeg)

Then I installed Tuya cloud in Homey, completed the configuration. The light showed up in Homey but it's not controllable 😅
![image](https://user-images.githubusercontent.com/85134/147756845-587dc113-f85c-40b6-a480-96a56070e07c.jpeg)

Diagnostics report ID is `cabb8dea-37cd-473d-a013-e8f00f22c229`

And thanks for the effort for creating this app💪💪🙏🙏

**Comment by jurgenheine** [comment]
Not entered correct username or password? See submitted log. Also try to use the test app, it uses the new official API.
See https://community.homey.app/t/app-pro-tuya-cloud/21313/407

Note: this log has been manually submitted by a user.
Log ID: cabb8dea-37cd-473d-a013-e8f00f22c229

User Message:
Device not controllable 



---- stdout ----
Discover devices
{"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}
Discover devices
{"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}
Discover devices
{"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}

**Comment by AndreLion** [comment]
Thanks for quick response.

Followed the guide for installing and setting up the new testing app. This time the light does not show up in Homey and no error was given.
![image](https://user-images.githubusercontent.com/85134/147761761-998ca569-ba92-4cff-8f81-b08b864bb4a5.png)


(tried restart the app and re-launch the Homey app)

Report ID: `1d8e0661-1ff2-4b47-b7f8-4a4064dbb809`

**Comment by jurgenheine** [comment]
You can't use your linked gmail account credentials as mentioned in the manual and in forum. You have to use a Tuya account.

**Comment by AndreLion** [comment]
> You can't use your linked gmail account credentials as mentioned in the manual and in forum. You have to use a Tuya account.

Both of them (Tuya IoT Platform & Tuya Smart app) are using same email address, and I tried both passwords, neither works. Then I changed the passwords same as each other, also does not work.

Thanks for your time and any other info I can provide to troubleshooting?
