### ISSUE TITLE
How to find Official api acces ID and Official api acces secret?

### ISSUE THREAD

**Issue by Jyo256** [jurgenheine/com.tuya.cloud#57]
Just installed Tuya cloud on my Homey.
Where asked when I configure the app to enter Official api acces ID and Official api acces secret, where do I find this info?

**Comment by JohPePe** [comment]
I’ve got a problem with the id’s too. Can’t get it to work.
Please help!

**Comment by panagiotismanolis** [comment]
Yes me too

**Comment by jurgenheine** [comment]
Double wirth other question.  #61
