### ISSUE TITLE
The app cannot dim to 1%

### ISSUE THREAD

**Issue by powermarcel10** [jurgenheine/com.tuya.cloud#6]
Hello and in the first place thanks for creating this plug and play app for Homey. Nice job.

I only find one (strange) thing. I have connected an Action LSC filament bulb and when I dim this bulb in homey using your app to 1%, in the tuya app it remains 4%. And when I set it to 1% in the tuya app it dims even further. Is this something you can fix?

Regards, 
Marcel

**Comment by jurgenheine** [comment]
This is unfortunately current behaviour, the cloud api is only accepting values between 10 - 100( color mode) or 10 - 256( White mode). So for color we can dim between 10% and 100% and for white mode we can dim between 4% and 100%.

**Comment by jurgenheine** [comment]
As workaround you can use a scene. Create a scene with the bulb(s) dimmed to 1% in the Tuya or Smart life app and call this scene in a Homey flow.

**Comment by powermarcel10** [comment]
> As workaround you can use a scene. Create a scene with the bulb(s) dimmed to 1% in the Tuya or Smart life app and call this scene in a Homey flow.

Thanks. I discovered that too. Working great! Thank for the reply. This one can be closed. Maybe good to explain this in the app information in the appstore for others.
