### ISSUE TITLE
Requires official api access id 

### ISSUE THREAD

**Issue by JohPePe** [jurgenheine/com.tuya.cloud#61]
![B3C8DD84-BDD6-41B3-94CA-F0B3E018711F](https://user-images.githubusercontent.com/25219053/152135084-db725f13-29e1-4bfb-bc69-07408f5c8f9e.jpeg)

is it possible to fix the issue?
Or can I install an earlier version?

**Comment by jurgenheine** [comment]
Maybe read the read.me or the community post on app. It's explained on both places.
https://community.homey.app/t/app-pro-tuya-cloud/21313
