### ISSUE TITLE
request to add tuya/zigbee smoke detector

### ISSUE THREAD

**Issue by Arzeg0** [jurgenheine/com.tuya.cloud#65]
Is it possible to add the smoke detector as device in the tuya cloud app.
If help is needed I am willing to try to help you.

**Comment by mvervoorn** [comment]
@Arzeg0  the Zigbee devices are supported but then in the tuya Zigbee app(https://community.homey.app/t/app-pro-tuya-zigbee-app/26439). The cloud app is more for wifi devices if I'm not mistaken. Nevertheless, I second this request but then for wifi detectors. The tuya wifi smoke detectors are the most cost-efficient, it would be great to see this support in the cloud app

Regards,

Maarten

**Comment by jurgenheine** [comment]
It should be possible with new API, but remeber this is Tuya **CLOUD**, so no local control updates

**Comment by jurgenheine** [comment]
added in latest test version
