### ISSUE TITLE
Continuous timeouts

### ISSUE THREAD

**Issue by SPorkka** [jurgenheine/com.tuya.cloud#75]
Hi, I cannot get it to work. Getting continously timeouts, while configure the app. While restarting the app. I have tried uninstalling and reinstalling.
The app has the paus mark on it. Even after reinstalling
Please advice
Kind regards 
Stefan

**Comment by jurgenheine** [comment]
It's resolved in next version
https://community.homey.app/t/app-pro-tuya-cloud/21313
