### ISSUE TITLE
Connecting Smartlife app to Homey

### ISSUE THREAD

**Issue by Grasduyn** [jurgenheine/com.tuya.cloud#76]
Hi Jurgen,

I’m trying to connect the iPhone Smartlife app to Homey. So I installed the Tuya cloud app on Homey. But then it asks me to sign in and fill in Api secret numbers and all. What do I fill in there?

regards, Roan

**Comment by jurgenheine** [comment]
https://community.homey.app/t/app-pro-tuya-cloud/21313
