### ISSUE TITLE
PIR not appearing in homey 

### ISSUE THREAD

**Issue by mvervoorn** [jurgenheine/com.tuya.cloud#77]
Hi @jurgenheine, I posted an issue on the homey communictie
https://community.homey.app/t/app-pro-tuya-cloud/21313/628?u=matrean
Seems my device is not appearing in the tuya cloud app on homey when adding a device. It is visible in the tuya IoT developer platform. 

Can you have a look at it. Thanks!

Maarten

**Comment by jurgenheine** [comment]
It's working now for you I saw on forum, so can be closed
