### ISSUE TITLE
Refresh tuya appliances in homey

### ISSUE THREAD

**Issue by kuiperonline** [jurgenheine/com.tuya.cloud#8]
How can I refresh the list with lights, switches etc.
I delete some switches and added others from en to the Tuya app.
These changes are not vissible in Tuya Cloud on my homey.

Thanks in advance
Vincent

**Comment by jurgenheine** [comment]
The list should be populated automaticly. If you start pairing lights in Homey, you should get all not already paired lights.

**Comment by kuiperonline** [comment]
![D2FB2AF8-9BA1-45CF-B7C5-A6D32EE1AFEF](https://user-images.githubusercontent.com/48593176/76192834-0524f500-61e3-11ea-83fc-df1051088f0c.png)

![29B157E8-55D9-46C8-889C-8B3ABF04BB30](https://user-images.githubusercontent.com/48593176/76192849-0c4c0300-61e3-11ea-9f8d-64bb9b797c60.png)


Jurgen,

There is a mismatch between my tuya app and homey. See screenshots

**Comment by jurgenheine** [comment]
Hmm, this looks strange, the icons are disapeared also.  Here are some steps and questions to try. Please report for each question the result. If you get errors in one of the questions, please send the error report. I looked at crash reports, but there are none last month.
Is the app enabled?
Did you try to delete them in Homey and add them again?
Did you try disable and enable again?
If you open app configuration and press save, do you get an error message?

**Comment by DIYglenn** [comment]
Not sure if this is resolved, but I had issues like that with multiple apps when my Homey’s PSU went bad. It supplied less than 4V.

**Comment by jurgenheine** [comment]
New API implemented, probably resolves this also.
