### ISSUE TITLE
Suggestion to improve responsiveness

### ISSUE THREAD

**Issue by frodeheg** [jurgenheine/com.tuya.cloud#81]
If I use this app to control my Tuya lights it takes 2 seconds before the lights react.
However, if I use the python API from https://github.com/jasonacox/tinytuya then I get instant response. (this too fetches the device list from the cloud so not much difference except that after the device list has been downloaded it communicates directly with the light instead of communicating through the cloud)
Would it be possible to use this API instead to get faster response on the lights?

**Comment by jurgenheine** [comment]
This is Cloud Tuya, there is an other Homey app for local control. Also the API you found is Python, Homey needs NodeJS.
