### ISSUE TITLE
Can not add new Device in Homey

### ISSUE THREAD

**Issue by DirkStorck** [jurgenheine/com.tuya.cloud#83]
Hi,

In Tuya Cloud I have 
![grafik](https://user-images.githubusercontent.com/2306190/164173051-3b0b16a2-b714-4e70-9e8d-281ef8df2c01.png)

and in the app  I have configured
![grafik](https://user-images.githubusercontent.com/2306190/164172948-d51414a6-98f4-47e7-a14e-336929965e5a.png)

1 matches 1 from first screenshot and 2 matches 2 from first screenshot

If I click on save I don't get an error and if I restart the app I don't get an error as well. 
But when I try to add a new device 

![grafik](https://user-images.githubusercontent.com/2306190/164173738-27298f1c-8ccf-4f2e-8ee0-6d318adeb78a.png)

I get 

![grafik](https://user-images.githubusercontent.com/2306190/164173771-3398786a-088b-477a-942c-eedcf01fcfbd.png)

any Idea?

Thank you

**Comment by jurgenheine** [comment]
Use the mobile app( smart life) username and password, and it's not allowed that this is a linked google accounts but it has to be a Tuya mobile app account. Do you see your devices in cloud environment, if not follow **all** the steps. What message do you get when press save on Homey app settings page, google this message. 

Tuya demands this new login methode, all the necessary steps are from Tuya tutorials. I liked the old API more with only username and password, but that one will be stopped soon and is also unusable with all the time-outs now.

**Comment by DirkStorck** [comment]
Hi,

I can see all my device in the cloud environment and if I hit the save button I don't get an error

![grafik](https://user-images.githubusercontent.com/2306190/164651655-79aef443-d03d-44d1-9680-f859e43c2797.png)

But I still get that message 

![grafik](https://user-images.githubusercontent.com/2306190/164651800-2689790e-43d3-4821-afb9-190370f6df16.png)

**Comment by jurgenheine** [comment]
Other points I mentioned?

**Comment by DirkStorck** [comment]
what other steps? Thanks!
