### ISSUE TITLE
Problem registrering , keep getting please configure app

### ISSUE THREAD

**Issue by Harryd1969** [jurgenheine/com.tuya.cloud#84]
Hello

installed the app

configured the Tuya cloud for connection to my Tuya smart account. All devices are in there

with all the details from Tuya cloud entered in the Tuya app for Homey i keep getting configure the app. I’ve checked everything numerous times, but no luck

can i send you a debug file for checking , or any other ideas?

harry

**Comment by jurgenheine** [comment]
In first post of forum is a guide how to setup. Also there a lot of links to tutorials.
