### ISSUE TITLE
Would like to get in contact with you

### ISSUE THREAD

**Issue by dheuts90** [jurgenheine/com.tuya.cloud#85]
Good afternoon Jurgen Heine,

We would like to get in contact with you to check the possibilities to add a connection to our new Hoftronic Smart app (to be launched) also to you Homey Tuya Cloud app. Can you please let me know how to get in contact? I tried sending a PM via the Homey Forum, but don't see the option to get in contact via a PM. Also on Github I don't see any options to get in contact.

Hope to hear from you, thanks a lot.

**Comment by jurgenheine** [comment]
Can you give me your Homey community username, I will try to send you a DM so we can share contact information.

**Comment by dheuts90** [comment]
Thanks!
Its Davy_Heuts

**Comment by jurgenheine** [comment]
I have sent an PB a week ago on the forum, You didn"t receive it?
