### ISSUE TITLE
Door/window and smoke detectors 

### ISSUE THREAD

**Issue by dyandh** [jurgenheine/com.tuya.cloud#87]
Hi Jurgen
I am using Homey and several Zigbee devices like  door/windows and smoke detectors to automate my house. I am using a ZigBee gateway to connect the ZigBee detectors to the Smart live application and this is working fine. But when integrating this to Homey using the Tuya Smart live interface, these devices are not showing up. ZigBee switches I defined in the same way on the gateway are showing and is working fine.

Items I am using:
- LIDL door/window sensors
- as in Holland smoke alarms are getting obligated to be used in all houses, I purchased the following smoke detection device: https://a.aliexpress.com/_mskZZcq

Is it possible to add them in your supported items?

Thanks for you help,
Dyan

**Comment by jurgenheine** [comment]
They are already supported. You are probably still using the old API. Switch to the new API, old API doesn't support sensors. See forum for steps and links to tutorials.
