### ISSUE TITLE
Support for smart human presence sensor

### ISSUE THREAD

**Issue by AdyRock** [jurgenheine/com.tuya.cloud#91]
Hi Jurgen,

Can you add support for the human presence sensor https://www.aliexpress.com/item/1005004019492542.html?spm=a2g0o.order_list.0.0.18751802J1eXD7

If there is anything I can do to help please let me know.

Thanks,
Adrian.

**Comment by jurgenheine** [comment]
Hi Adrian,

I expected that this sensor already was supported in the test version. If not, can you send me a diagnostic report so I can look what's wrong. I asume you already looked if the device is showing in Tuya developer portal, when it's not showing there, it's not possible to use the device.

If the device is present in Tuya developer portal, you can probably already use the sensor with the new "Text event received". If you use this card en send the output to logging, you get the device id and functions with their values. When you know the data you need, you can change the flow or create a new one and use those as filters or send it to a virtual device. There are several receive flow cards and also several send flow cards. With those flows an advanced user can use all devices who are shown in Tuya developer portal.

**Comment by AdyRock** [comment]
Hi Jurgen, 

I grabbed the code from your git repo and added the device. I will create a pull request so you can verify it and merge.

**Comment by AdyRock** [comment]
I have created a pull request for the new device.

**Comment by jurgenheine** [comment]
The pull request is merged and the changes are published to the test version. Thanks for adding the sensor :)

**Comment by AdyRock** [comment]
Great work on the app, so happy to support it, even if it is for my own needs :-) .

**Comment by jurgenheine** [comment]
Thanks for compliment and your contribution to the app. I started to develop on the app also for own needs , but then become enthousiast to support more devices. But I also find out that supporting devices you don't own is little bit harder then I thought.

**Comment by AdyRock** [comment]
I know the problem, hence I build in as much diagnostics as possible 😉

**Comment by jurgenheine** [comment]
I agree, logging is important.
