### ISSUE TITLE
Nedis Smart Plug Energy - Power consumption not shown i Homey device

### ISSUE THREAD

**Issue by MagnusBjelksjo** [jurgenheine/com.tuya.cloud#93]
Nedis Smart Plug Energy - Power consumption not shown i Homey device.

The device is added to Homey Pro and On/Off-command can be properly sent.

But in Homey information about power consumption is not shown. It only tells "0 W".

As reference test i open the "Smartlife" iOS-App and there i can see the level of power consumption.

Why is it like this?

**Comment by jurgenheine** [comment]
Use the new API or it's not supported.

**Comment by MagnusBjelksjo** [comment]
> Use the new API or it's not supported.

I have only installed Tuya Cloud on Homey. Where can i make s choice which API to be used?
