### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by eeckelaertyannick** [jurgenheine/com.tuya.cloud#94]
Hi jurghen, I'm experiencing problems for a wile, when I restart Homey the are connection problems whit the tja homey tuya cloud api. The is nog connection. I need to restart the app ent end do some thing to genus the connection. Alsow renew the inlog info etc en then after a few try's is connects again. Every time home restarts can you help out? ff49976e-33fb-481a-99a0-bf4f26049f93

**Comment by jurgenheine** [comment]
You are still using the old,depricated and no longer supported API. Tuya is increasing the time-out of this API and therefore all the issues arise. Swith to new API. See forum thread and several Howto's in the thread.

**Comment by eeckelaertyannick** [comment]
Jurgen, stel 2 end 3 : 

In the left-side navigation bar, choose Cloud.

On the page that appears, click Create Cloud Project.

I can not find them. Maybe the platform is changed?

Sry for the question I'm not an expert.

**Comment by jurgenheine** [comment]
I don't know either, Long time ago I created it myself.  The guides and tutorials are from Tuya and I am linking to them. Maybe it;s changed and they still have to update their documentatiion.

**Comment by eeckelaertyannick** [comment]
I am a noob ath this could you tell me how to get the way to do this? Because I want to use the app in full.

**Comment by eeckelaertyannick** [comment]
@jurgenheine, i managed tot change the login information. But stil have te problem that every time home restarts the tuya app dos not get connection whit the cloud. When I re enter the credentials it works again until update ore restart. En it happens al over again can you advice please?
