### ISSUE TITLE
No new devices has been found

### ISSUE THREAD

**Issue by kontajnersk** [jurgenheine/com.tuya.cloud#95]
Dear Developer, I would like to kindly ask for support, I am not able to add Tuya ceiling panel light to Homey. Everytime I got message " No new devices has been found". I reinstalled app, swithed from Tuya to SmartLife, recreated other accounts for app and IoT, recreated Cloud projects, relinked app with IOT Cloud Project (device is shown and linked to project) - with no success. My ceiling panel light is in Tuya/SmarLife app discovered as WYRGB-Light. In reality, it is this product: https://www.moemax.at/p/premium-living-led-deckenleuchte-geoer-max-30-watt-0082270960
Can You please chceck diagnostic report a58db437-8f00-40ed-9074-6a2cb0baa565.
Thanks in advance, Konti

**Comment by jurgenheine** [comment]
Is your devices shown in Tuya developer portal? If iit's not shown there, it's not supported or you made somewhere an error between linking app, region in portal is not correct, wrong app, I don't kown, there are no errors in the log, and you are succesfull loggedin. Also there are no devices, found as you already discovered. Look at forum thread if somebody had the same as you and what the solutions was.

**Comment by kontajnersk** [comment]
I wrote "device is shown and linked to project", your response starts with "Is your devices shown in Tuya developer portal?". Can I get somehow access to  log file to study my problem more deeply?  Access to log file limited solely to developer can lead to responses like above - I have motivation, you have information (and vice versa).
