### ISSUE TITLE
Missing device category mbd

### ISSUE THREAD

**Issue by kontajnersk** [jurgenheine/com.tuya.cloud#96]
Dear Jurgenheine, this ticket follow #95, where I reported "no new devices have been found". For test I did the same procedure on HASSIO/Home Assistant with same settings and my Ceiling LED Panel was found and added immediatly. It means, that "problem" is in Homey implementation of Tuya Cloud. I checked HASSIO diagnostic file(in attachement) and I found "category": "mbd", which can be reason, why device is not imported. This category was added to Home Assistant in 3/2022. https://github.com/home-assistant/core/pull/65918
Can You please confirm, that category mbd is currently not supported and eventualy to plan impelemntation of mbd support?
Thanks, Konti

[tuya-67390e341dde40f110053f2fec87c126-WYRGB-Light-9e6f34f5da8ec256f70304bd18c9ebc3.json.txt](https://github.com/jurgenheine/com.tuya.cloud/files/9203686/tuya-67390e341dde40f110053f2fec87c126-WYRGB-Light-9e6f34f5da8ec256f70304bd18c9ebc3.json.txt)

**Comment by jurgenheine** [comment]
Added the category to the list of light types, I didn't know the mbd category. You can try it in the latest test version

**Comment by kontajnersk** [comment]
Dear Jurgeheine, I tried mentioned improoved test version and I can confirm, that my ceiling led panel was now recognised immediatly. Missing product category "mbd" was problem. I tested my LED panel control from Homey and everything works perfectly - on/off, brightness, color.
Many thanks, Konti 
PS: you can apply improvement to general release
